#!/usr/bin/python3

import sys
import os
import requests
from bs4 import BeautifulSoup

def problem_exists(problemid):
    link = 'http://www.infoarena.ro/problema/' + problemid
    page = requests.get(link)
    soup = BeautifulSoup(page.content, 'html.parser')
    if soup.findAll("div", {"id" : "flash"}) == []:
        print ('problem exists')
        return 1
    else:
        print('problem does not exist')
        return 0

def fetch_example(problemid):
    if not problem_exists(problemid):
        print ('Could not fetch example. Eror: Problem does NOT exist.')
        return
    link = 'http://www.infoarena.ro/problema/' + problemid
    page = requests.get(link)
    soup = BeautifulSoup(page.content, 'html.parser').find("table", {"class":"example"})

    example = soup.findAll("td")
    return (example[0].text, example[1].text)

def main():
    if len(sys.argv) < 2:
        print ('Not enough parameters')
    else:
        fetch_example(sys.argv[1])

if __name__ == '__main__':
    main()
